-- ? 1. Script Oracle 19c (Tabla + Datos)
-- Tabla de productos de papelería
CREATE TABLE PRODUCTOS_PAPELERIA (
    ID          NUMBER PRIMARY KEY,
    NOMBRE      VARCHAR2(100),
    PRECIO      NUMBER(10,2),
    STOCK       NUMBER
);

COMMIT;

-- Datos de ejemplo
INSERT INTO PRODUCTOS_PAPELERIA VALUES (1, 'Cuaderno', 5000, 20);
INSERT INTO PRODUCTOS_PAPELERIA VALUES (2, 'Lapiz', 1000, 50);
INSERT INTO PRODUCTOS_PAPELERIA VALUES (3, 'Borrador', 800, 30);
INSERT INTO PRODUCTOS_PAPELERIA VALUES (4, 'Regla', 1500, 15);
INSERT INTO PRODUCTOS_PAPELERIA VALUES (5, 'Marcador', 2500, 25);

COMMIT;

--? 2. Procedimiento Almacenado (UPDATE)
CREATE OR REPLACE PROCEDURE ACTUALIZAR_PRODUCTO (
    P_ID        IN NUMBER,
    P_NOMBRE    IN VARCHAR2,
    P_PRECIO    IN NUMBER,
    P_STOCK     IN NUMBER
)
IS
BEGIN
    UPDATE PRODUCTOS_PAPELERIA
    SET 
        NOMBRE = P_NOMBRE,
        PRECIO = P_PRECIO,
        STOCK = P_STOCK
    WHERE ID = P_ID;

    COMMIT;
END;
/

COMMIT;